### ISSUE TITLE
ADD PYTHON_TUTORIAL

### ISSUE THREAD

**Issue by Coder-Harshit** [thegeekyb0y/learnpython#10]
Content Creator : Programming With Mosh
Views on Youtube : 800K+

![PYTHON TUTORIALS](https://youtube.com/playlist?list=PLTjRvDozrdlxj5wgH4qkvwSOdHLOCx10f)

Description : Good & Clear Content Delivery of Python Programming Language.

**Comment by thegeekyb0y** [comment]
Create A PR instead
