### ISSUE TITLE
Add offcial docs/libraries links

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [thegeekyb0y/learnpython#14]
In the roadmap.md file, we can add official docs links for each library/framework we mentioned for Python applications. e.g. TensorFlow, Sci-kit Learn, etc.

**Comment by thegeekyb0y** [comment]
Yeah , definitely, you can make a PR to do it

**Comment by anubhav1206** [comment]
Can I work on it?

**Comment by thegeekyb0y** [comment]
sure, go ahead
