### ISSUE TITLE
Can you add Spanish translations of the readme.md for non-English speakers ?

### ISSUE THREAD

**Issue by Fer-Bar** [thegeekyb0y/learnpython#20]
I could translate the README.md into Spanish and add resources in that language.

**Comment by thegeekyb0y** [comment]
ok do

**Comment by thegeekyb0y** [comment]
ok do

**Comment by thegeekyb0y** [comment]
create a seperate readme file to do it

**Comment by Fer-Bar** [comment]
> create a seperate readme file to do it

Okey @thegeekyb0y I gonna work in that can you assign me this issue?
