### ISSUE TITLE
Add automate the Boring Stuff with Python

### ISSUE THREAD

**Issue by GLGub** [thegeekyb0y/learnpython#26]
Hi,
Can you add Automate the Boring Stuff with Python
By Al Sweigart?
Its beginner friendly. 

Link below
https://automatetheboringstuff.com/#toc

Thanks

**Comment by thegeekyb0y** [comment]
Hello,

You can create a PR and I will merge it.

**Comment by Darshan016** [comment]
If you want i can add that

**Comment by thegeekyb0y** [comment]
sure

**Comment by Darshan016** [comment]
added the resource

**Comment by anubhav1206** [comment]
Its still open, can i work on it?
